---
title: "Biography"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Education

**Columbia University | New York, NY**

*Master of Science in Biostatistics | Sep. 2023 - May 2025*

* Track: Public Health Data Science
* Courses: Data Science, Biostatistical Methods, Principles of Epidemiology, Probability, etc.

**East China Normal University | Shanghai, China**

*Bachelor of Science in Statistics | Sep. 2019 - Jun. 2023*

* GPA:3.67/4.00
* Courses: Design of Experiments, Statistical Learning, Multivariate Statistical Analysis, Statistical and computational methods in Biomedicine, etc.

# Technical Proficiencies

R, Python, Latex, SQL, Microsoft Excel, Microsoft PowerPoint

# Work Experience

**Medtronic | Shanghai, China**

*Data Intelligence Intern | Nov. 2022 - May 2023*

* Designed and implemented a geographically stratified sampling scheme to assess data quality across more than 3000 hospitals.
* Restructured the sales staff and streamlined the hospital's data uploads, resulting in improved efficiency of job updates.
* Utilized R to clean and analyze hospital data, generating reports on potential hospitals for targeted initiatives.

**Deloitte | Chongqing, China**

*Data Analyst Intern | Jun. 2022 - Sep. 2022*

* Participated in a project to identify the needs of more than 5000 commercial bank clients for healthcare companies and applied R to perform data comparison in the healthcare industry on the Deloitte DSI platform.
* Utilized Python to crawl corporate information missing from the database, categorized the medical companies into different levels based on their industrial data.
* Used random forest to conduct missing data imputation, and carried out prediction of debt-issuing corporate.


# Research Experience

**CUIMC Biostatistics Department**

*Reaserch Assistant | Sept. 2023 - Now*

* Developing statistical methods for multi-sample single-cell transcriptomics data.


**HKUST Mathematics Department**

*Intern Researcher | Jul. 2022 - Aug. 2022*

* Derived equations and implemented Python code for the gradient boosting algorithm to estimate parameters in a regression model optimized for categorical data.
* Conducted equation derivation and code implementation of EM (Expectation-Maximization) and VIEM (Variational Inference for Expectation-Maximization) for fitting linear mixed models.
* Built a PSD (Population Structure Detection) model using various algorithms, including MCMC (Markov Chain Monte Carlo), stochastic variational inference, and sequential quadratic programming, to perform ancestry inference on a dataset of 1000k+ genetic data.

