---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Column {data-width=500}
-----------------------------------------------------------------------
### Boxplot

```{r}
data("instacart")
instacart = 
  instacart |> 
  select(
    aisle, product_name, order_hour_of_day) |>
  filter(
    !is.na(aisle), 
    !is.na(product_name), 
    !is.na( order_hour_of_day))
```

```{r}
instacart|>
  group_by(aisle,order_hour_of_day)|>
  mutate(n_order=n())|>
  filter(n_order>1000)|>
  plot_ly(x = ~aisle, y = ~order_hour_of_day,color=~aisle, type = "box",colors="viridis")
```



Column {data-width=500}
-----------------------------------------------------------------------

### Lineplot

```{r}
instacart|>
  group_by(order_hour_of_day)|>
  summarize(n_products=n())|>
  filter(n_products>3000)|>
  plot_ly( x = ~order_hour_of_day, y = ~n_products, type = "scatter", mode = "lines") 
```


### Barplot

```{r}
instacart|>
  group_by(aisle)|>
  summarize(n_products=n())|>
  filter(n_products>10000)|>
  mutate(aisle=fct_reorder(aisle,n_products))|>
  plot_ly(x=~aisle,y=~n_products,color=~aisle,type="bar",colors="viridis")
```

